#!/bin/bash

conda activate svdiff

cd ~/svdiff-pytorch


accelerate launch train_svdiff.py --pretrained_model_name_or_path="/home/ldnigogosova/stable-diffusion-2-base" --instance_data_dir="/home/ldnigogosova/datasets/dreambooth/dataset/dog6" --class_data_dir="prior_images_dog" --output_dir="output_dog" --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="a sks dog" --class_prompt="a dog" --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=1e-3 --learning_rate_1d=1e-6 --train_text_encoder --lr_scheduler="constant" --lr_warmup_steps=0 --num_class_images=1000 --max_train_steps=2000 --report_to="wandb" --validation_prompt="a sks dog in the jungle[EOS]a sks dog on the beach[EOS]a sks dog on top of a wooden floor[EOS]a sks dog wearing a rainbow scarf[EOS]a purple sks dog" --validation_epochs=1 --checkpointing_steps=200 --seed="0" --train_batch_size=4 --sample_batch_size=10
accelerate launch train_svdiff.py --pretrained_model_name_or_path="/home/ldnigogosova/stable-diffusion-2-base" --instance_data_dir="/home/ldnigogosova/datasets/dreambooth/dataset/backpack" --class_data_dir="prior_images_backpack" --output_dir="output_backpack" --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="a sks backpack" --class_prompt="a backpack" --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=1e-3 --learning_rate_1d=1e-6 --train_text_encoder --lr_scheduler="constant" --lr_warmup_steps=0 --num_class_images=1000 --max_train_steps=2000 --report_to="wandb" --validation_prompt="a sks backpack in the jungle[EOS]a sks backpack on the beach[EOS]a sks backpack on top of a wooden floor[EOS]a wet sks backpack[EOS]a purple sks backpack" --validation_epochs=1 --checkpointing_steps=200 --seed="0" --train_batch_size=4 --sample_batch_size=10
accelerate launch train_svdiff.py --pretrained_model_name_or_path="/home/ldnigogosova/stable-diffusion-2-base" --instance_data_dir="/home/ldnigogosova/datasets/dreambooth/dataset/cat" --class_data_dir="prior_images_cat" --output_dir="output_cat" --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="a sks cat" --class_prompt="a cat" --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=1e-3 --learning_rate_1d=1e-6 --train_text_encoder --lr_scheduler="constant" --lr_warmup_steps=0 --num_class_images=1000 --max_train_steps=2000 --report_to="wandb" --validation_prompt="a sks cat in the jungle[EOS]a sks cat on the beach[EOS]a sks cat on top of a wooden floor[EOS]a sks cat wearing a rainbow scarf[EOS]a purple sks cat" --validation_epochs=1 --checkpointing_steps=200 --seed="0" --train_batch_size=4 --sample_batch_size=10

