#!/bin/bash

conda activate cuda

cd ~/diffusers/examples/dreambooth

accelerate launch train_dreambooth.py --pretrained_model_name_or_path="/home/ldnigogosova/stable-diffusion-2-base" --instance_data_dir="/home/ldnigogosova/datasets/dreambooth/dataset/dog6" --class_data_dir="dreambooth_prior_images_dog" --output_dir="trained_dreambooth_dog" --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="a sks dog" --class_prompt="a dog" --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-6 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=2000 --report_to="wandb" --validation_prompt="a sks dog in the jungle[EOS]a sks dog on the beach[EOS]a sks dog on top of a wooden floor[EOS]a sks dog wearing a rainbow scarf[EOS]a purple sks dog" --validation_steps=200 --checkpointing_steps=200 --seed="0" --num_class_images=1000 --sample_batch_size=10
accelerate launch train_dreambooth.py --pretrained_model_name_or_path="/home/ldnigogosova/stable-diffusion-2-base" --instance_data_dir="/home/ldnigogosova/datasets/dreambooth/dataset/backpack" --class_data_dir="dreambooth_prior_images_backpack" --output_dir="trained_dreambooth_backpack" --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="a sks backpack" --class_prompt="a backpack" --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-6 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=2000 --report_to="wandb" --validation_prompt="a sks backpack in the jungle[EOS]a sks backpack on the beach[EOS]a sks backpack on top of a wooden floor[EOS]a wet sks backpack[EOS]a purple sks backpack" --validation_steps=200 --checkpointing_steps=200 --seed="0" --num_class_images=1000 --sample_batch_size=10
accelerate launch train_dreambooth.py --pretrained_model_name_or_path="/home/ldnigogosova/stable-diffusion-2-base" --instance_data_dir="/home/ldnigogosova/datasets/dreambooth/dataset/cat" --class_data_dir="dreambooth_prior_images_cat" --output_dir="trained_dreambooth_cat" --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="a sks cat" --class_prompt="a cat" --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-6 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=2000 --report_to="wandb" --validation_prompt="a sks cat in the jungle[EOS]a sks cat on the beach[EOS]a sks cat on top of a wooden floor[EOS]a sks cat wearing a rainbow scarf[EOS]a purple sks cat" --validation_steps=200 --checkpointing_steps=200 --seed="0" --num_class_images=1000 --sample_batch_size=10

accelerate launch train_dreambooth_lora.py --pretrained_model_name_or_path="/home/ldnigogosova/stable-diffusion-2-base" --instance_data_dir="/home/ldnigogosova/datasets/dreambooth/dataset/dog6" --class_data_dir="lora_prior_images_dog" --output_dir="trained_lora_dog_rank_4" --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="a sks dog" --class_prompt="a dog" --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --checkpointing_steps=100 --learning_rate=1e-4 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=2000 --validation_prompt="a sks dog in the jungle[EOS]a sks dog on the beach[EOS]a sks dog on top of a wooden floor[EOS]a sks dog wearing a rainbow scarf[EOS]a purple sks dog" --validation_epochs=1 --seed="0" --report_to="wandb" --num_class_images=1000 --rank=4 --sample_batch_size=10
accelerate launch train_dreambooth_lora.py --pretrained_model_name_or_path="/home/ldnigogosova/stable-diffusion-2-base" --instance_data_dir="/home/ldnigogosova/datasets/dreambooth/dataset/backpack" --class_data_dir="lora_prior_images_backpack" --output_dir="trained_lora_backpack_rank_4" --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="a sks backpack" --class_prompt="a backpack" --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --checkpointing_steps=100 --learning_rate=1e-4 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=2000 --validation_prompt="a sks backpack in the jungle[EOS]a sks backpack on the beach[EOS]a sks backpack on top of a wooden floor[EOS]a wet sks backpack[EOS]a purple sks backpack" --validation_epochs=1 --seed="0" --report_to="wandb" --num_class_images=1000 --rank=4 --sample_batch_size=10
accelerate launch train_dreambooth_lora.py --pretrained_model_name_or_path="/home/ldnigogosova/stable-diffusion-2-base" --instance_data_dir="/home/ldnigogosova/datasets/dreambooth/dataset/cat" --class_data_dir="lora_prior_images_cat" --output_dir="trained_lora_cat_rank_4" --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt="a sks cat" --class_prompt="a cat" --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --checkpointing_steps=100 --learning_rate=1e-4 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=2000 --validation_prompt="a sks cat in the jungle[EOS]a sks cat on the beach[EOS]a sks cat on top of a wooden floor[EOS]a sks cat wearing a rainbow scarf[EOS]a purple sks cat" --validation_epochs=1 --seed="0" --report_to="wandb" --num_class_images=1000 --rank=4 --sample_batch_size=10